#ifndef __CUSTSENSOR_EXT_INTERFACE__
#define __CUSTSENSOR_EXT_INTERFACE__


typedef enum
{
    AE_CUSTOM_TRANSFORM_START = 0,
    AE_CUSTOM_TRANSFORM_BINSUM = AE_CUSTOM_TRANSFORM_START,
    AE_CUSTOM_TRANSFORM_ATR,
    AE_CUSTOM_TRANSFORM_NUM
} AE_CUSTOM_TRANSFORM_ENUM;

#endif

