CCU_TOOL_SENSOR_DIR := $(LOCAL_PATH)/$(MTK_PLATFORM_DIR)/sensor
CCU_TOOL_LENS_DIR := $(LOCAL_PATH)/$(MTK_PLATFORM_DIR)/lens
CCU_TOOL_CUSTSENSOR_DIR := $(LOCAL_PATH)/$(MTK_PLATFORM_DIR)/custsensor
CCU_TOOL_CUSTFUNC_DIR := $(LOCAL_PATH)/$(MTK_PLATFORM_DIR)/custfunc
CCU_TOOL_COMMON_DIR := $(LOCAL_PATH)/$(MTK_PLATFORM_DIR)/common

include $(CCU_TOOL_LENS_DIR)/Android.mk
include $(CCU_TOOL_SENSOR_DIR)/Android.mk
include $(CCU_TOOL_CUSTSENSOR_DIR)/Android.mk
include $(CCU_TOOL_CUSTFUNC_DIR)/Android.mk
